spring.application.name=soat-tech-challenge

# Conexão com valores padrão para rodar localmente
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/oficina?serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate