spring.application.name=soat-tech-challenge

# Conexão com valores padrão para rodar localmente
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/oficina?serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

jwt.secret=${JWT_SECRET:7K#9vX$2mP*4wL@8zQ!6fB%1hN*3jD#5sFull}
jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:60}

# Logging configuration
logging.level.root=INFO
logging.level.com.oficina=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Expose all endpoints to help with debugging if needed (optional)
# management.endpoints.web.exposure.include=*
